### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by bnubald** [softwaresaved/SSI-Website-Issues#1]
Hi, just noticed two links pointing to potentially old pages [here](https://www.software.ac.uk/about/contact-us). These links currently give a 404 error.

* [x] "News & Blog" should point to https://www.software.ac.uk/news-and-blogs-hub
* [ ] "Newsletter" I believe should point to the same link in the subscribe button in the footer? (https://software.us7.list-manage.com/subscribe?u=628ee3fc74b8ef3497e3a7b66&id=087eeb655a)

**Comment by selina-aragon** [comment]
@bnubald Thank you for submitting these. We've fixed them. Let us know if you encounter further issues.
