### ISSUE TITLE
Update funding information for SSI-4

### ISSUE THREAD

**Issue by npch** [softwaresaved/SSI-Website-Issues#7]
Can the [Our Funders](https://www.software.ac.uk/about/our-funders) page on the website be updated to reflect the new funding, and also correct some typos / add necessary information.

The new text is below:

____

**Initially funded by the Engineering and Physical Sciences Research Council (EPSRC), and subsequently having received funding from all seven UK research councils, the SSI is currently funded by UK Research and Innovation (UKRI) through their Digital Research Infrastructure (DRI) programme.** 

The core funding for the SSI has come from the following sources:

- Phase 1 (2010-2015): EPSRC; £4.4m; [EP/H043160/1](https://gtr.ukri.org/projects?ref=EP%2FH043160%2F1).

- Phase 2 (2015-2018): EPSRC, ESRC, BBSRC £3.5m; [EP/N006410/1](https://gtr.ukri.org/projects?ref=EP%2FN006410%2F1).

- Phase 3 (2018-2024): AHRC, BBSRC, EPSRC, ESRC, MRC, NERC, STFC; £6.8m; [EP/S021779/1](http://gtr.ukri.org/projects?ref=EP%2FS021779%2F1).

- Phase 4 (2024-2028): UKRI; £8.1m; [AH/Z000114/1](http://gtr.ukri.org/projects?ref=AH%2FZ000114%2F1).

The SSI has also pursued a fruitful strategy of collaborating with others to secure additional funding. During Phase 3, we were involved in 13 projects totalling £22.8m, and led a further five projects, all with the principal aims of developing new training pathways and undertaking research to inform policymakers. Collaborating in this way has allowed us to build on our core activities and deliver our work to new communities.

____

**Comment by Denis-Barclay** [comment]
This has now been updated.
